### ISSUE TITLE
Research on Firebase Cloud Functions

### ISSUE THREAD

**Issue by ShashinGounden** [Memory-Lane-COS301/miniproject-2023#2]
Please do research on **_Firebase Cloud Functions_** and how we will use them in our system. This is to prepare you for when we start with the implementation of the back end next week.

In addition to this: Make sure you are familiar with NestJS and  Firebase environments and deployment.

Will check in on Friday's meeting.

**Comment by ArmandKrynauw** [comment]
For the most part, we seem to be understanding the API stack and project structure. This issue can be close🙂
