### ISSUE TITLE
Integration Testing - Research

### ISSUE THREAD

**Issue by ShashinGounden** [Memory-Lane-COS301/miniproject-2023#34]
Please do research to familiarise yourself with implementing integration tests.

**Comment by P3TROOS** [comment]
Did research on a few solutions to do integration testing. We went with Travis Ci but are currently having issues setting up organizations in Travis Ci. Will post an update and close the issue when everything is sorted.

**Comment by P3TROOS** [comment]
Got Travis Ci to integrate with our repo and are currently setting it up. This concludes out integration testing research.
