### ISSUE TITLE
Update documentation for our CI/CD pipeline

### ISSUE THREAD

**Issue by ShashinGounden** [Memory-Lane-COS301/miniproject-2023#37]
Please update the documentation (Wiki) according to the new additions to the CI/CD pipeline. (JEST unit tests on front-end, back-end, and integration tests)

**Comment by P3TROOS** [comment]
Updated the CI-CD dcumantation, just need to confirm a few things before closing the issue.

**Comment by ShashinGounden** [comment]
Looks good so far.

**Comment by P3TROOS** [comment]
Finalized the documentation for CI-CD. Everything looks correct.
