### ISSUE TITLE
Setup ESLint

### ISSUE THREAD

**Issue by ShashinGounden** [Memory-Lane-COS301/miniproject-2023#50]
Please set up ESLint for local development and local listing.

**Comment by Bandisa** [comment]
Currently finishing this up. It should be completed by the end of the day.

**Comment by Bandisa** [comment]
- I have opted to build a new base eslint config file, one that is easy to understand, 
-I added simple rules, on top of extending the **standard-with-typescript** rule
-building a wiki now
-will communicate with devOps to also use this configuration during builds

**Comment by Bandisa** [comment]
> I have set-up a short wiki on how to lint locally, and provided an explanation for some of the rules for understanding purposes
>I had a meeting with @P3TROOS discussing how we going to use the local linting file on git too
>Once @P3TROOS obtains approval from the rest of the DevOps team, I will set up the gitHub super linter to use the same rules as locally.

**Comment by Bandisa** [comment]
Spoke to the DevOps team.
They will be completing the remainder of this issue.
Main take-way:
>prettier is already set-up with some basic rules for local configurations
>git is currently set-up to use prettier
>so they will either translate the ones on eslint to prettier, set-up a new config or set git to use the eslint rules for typescript only
