### ISSUE TITLE
GetUserCommand security bug

### ISSUE THREAD

**Issue by ArmandKrynauw** [Memory-Lane-COS301/miniproject-2023#98]
The GetUser request at the moment requires the username and then returns all the user details connected with that username. Since the backend has no authentication, any party can retrieve all user details, including their userId. We might have to change this get request by username to getting by userId rather. But maybe just put a hold on this for now if there is other work that has to be done.

**Comment by Bandisa** [comment]
Okay. Just changed it.
Will add some authentication for the endPoints after going through more issues.

**Comment by ShashinGounden** [comment]
Completed and merged
